const KEY='booze-control-v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state=load(); let month=9; let selectedDay=null;
function blank(){return {entries:[],staged:{day:'',drinks:[]}}}
function load(){try{return {...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return blank()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function pad(n){return String(n).padStart(2,'0')}
function trackingDay(d=new Date()){const x=new Date(d.getTime()-4*3600000);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`}
function autoSubmit(){if(!state.staged?.drinks?.length)return;const cur=trackingDay();if(state.staged.day&&state.staged.day<cur) commitStaged(state.staged.day)}
function stage(name){autoSubmit();name=name.trim();if(!name)return;const day=trackingDay();if(state.staged.drinks.length&&state.staged.day!==day)commitStaged(state.staged.day);if(!state.staged.drinks.length)state.staged.day=day;state.staged.drinks.push(name);save();render();toast()}
function commitStaged(day=state.staged.day||trackingDay()){if(!state.staged.drinks.length)return;state.staged.drinks.forEach((name,i)=>state.entries.push({id:crypto.randomUUID?.()||`${Date.now()}-${i}`,name,day}));state.staged={day:'',drinks:[]};save();render()}
function removeStaged(name){const i=state.staged.drinks.map(x=>x.toLowerCase()).lastIndexOf(name.toLowerCase());if(i>=0)state.staged.drinks.splice(i,1);if(!state.staged.drinks.length)state.staged.day='';save();render()}
function removeCommitted(day,name){for(let i=state.entries.length-1;i>=0;i--){if(state.entries[i].day===day&&state.entries[i].name.toLowerCase()===name.toLowerCase()){state.entries.splice(i,1);break}}save();render();if(selectedDay)openDetail(selectedDay)}
function grouped(list){return [...list.reduce((m,x)=>(m.set(x,(m.get(x)||0)+1),m),new Map())].sort((a,b)=>a[0].localeCompare(b[0]))}
function countDay(day){return state.entries.filter(e=>e.day===day).length}
function renderHome(){const sc=state.staged.drinks.length,submitted=countDay(trackingDay());$('#stagedCount').textContent=`Staged · ${sc} ${sc===1?'drink':'drinks'}`;$('#submittedCount').textContent=`Submitted today · ${submitted} ${submitted===1?'drink':'drinks'}`;$('#submitBtn').disabled=!sc;const el=$('#stagedList');el.innerHTML='';const gs=grouped(state.staged.drinks);if(!gs.length)el.innerHTML='<div class="empty">Nothing staged yet</div>';gs.forEach(([name,count])=>{const b=document.createElement('button');b.className='pill';b.textContent=`${name} ×${count}   ·   tap to remove 1`;b.onclick=()=>removeStaged(name);el.appendChild(b)})}
function renderCalendar(){const title=new Date(2026,month-1,1).toLocaleString(undefined,{month:'long',year:'numeric'});$('#monthTitle').textContent=title;const grid=$('#calendarGrid');grid.innerHTML='';const first=new Date(2026,month-1,1),offset=first.getDay(),days=new Date(2026,month,0).getDate();for(let i=0;i<offset;i++){const s=document.createElement('span');grid.appendChild(s)}for(let day=1;day<=days;day++){const key=`2026-${pad(month)}-${pad(day)}`,count=countDay(key);const b=document.createElement('button');b.className='day'+(count?' active-day':'');b.innerHTML=`<span>${day}</span>${count?`<span class="glass">🍸</span>`:''}${count>=2?'<i class="dot"></i>':''}`;b.onclick=()=>openDetail(key);grid.appendChild(b)}}
function openDetail(day){selectedDay=day;const d=new Date(day+'T12:00:00');$('#detailDate').textContent=d.toLocaleString(undefined,{month:'long',day:'numeric'});const list=$('#detailList');list.innerHTML='';const items=state.entries.filter(e=>e.day===day).map(e=>e.name),gs=grouped(items);if(!gs.length)list.innerHTML='<div class="empty">No drinks logged</div>';gs.forEach(([name,count])=>{const b=document.createElement('button');b.className='pill';b.textContent=`${name} ×${count}   ·   tap to remove 1`;b.onclick=()=>removeCommitted(day,name);list.appendChild(b)});const total=items.length;$('#detailTotal').textContent=`${total} ${total===1?'drink':'drinks'}`;$('#detailOverlay').classList.add('show');$('#detailOverlay').setAttribute('aria-hidden','false')}
function closeDetail(){selectedDay=null;$('#detailOverlay').classList.remove('show');$('#detailOverlay').setAttribute('aria-hidden','true')}
function render(){autoSubmit();renderHome();renderCalendar()}
function switchScreen(name){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+name).classList.add('active');$('#homeTab').classList.toggle('active',name==='home');$('#calendarTab').classList.toggle('active',name==='calendar');if(name==='calendar')renderCalendar()}
function toast(){const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),800)}
$$('.quick-card').forEach(b=>b.onclick=()=>stage(b.dataset.drink));$('#otherAdd').onclick=()=>{stage($('#otherInput').value);$('#otherInput').value=''};$('#otherInput').addEventListener('keydown',e=>{if(e.key==='Enter'){$('#otherAdd').click();e.target.blur()}});$('#submitBtn').onclick=()=>commitStaged();$('#homeTab').onclick=()=>switchScreen('home');$('#calendarTab').onclick=()=>switchScreen('calendar');$('#prevMonth').onclick=()=>{if(month>9){month--;renderCalendar()}};$('#nextMonth').onclick=()=>{if(month<12){month++;renderCalendar()}};$('#closeDetail').onclick=closeDetail;$('#detailOverlay').addEventListener('click',e=>{if(e.target.id==='detailOverlay')closeDetail()});
setInterval(()=>{autoSubmit();renderHome()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){autoSubmit();render()}});
render();
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
